---
apiVersion: v1
kind: ConfigMap
metadata:
  name: APP-config-map
data:
  app_settings: "APP_CONFIG"
  dev_database_url: "postgresql://DB_USER:DB_PWD@DB_NAME/APP"
  secret_key: "APP_KEY"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APP
  name: APP-deployment
  namespace: SERVICENAME
spec:
  selector:
    matchLabels:
      app: APP
  replicas: 2
  template:
    metadata:
      labels:
        app: APP
    spec:
      containers:
      - name: web
        image: ImageName
        env:
        - name: APP_SETTINGS
          valueFrom: 
            configMapKeyRef:
              name: APP-config-map
              key: app_settings
        - name: DEV_DATABASE_URL
          valueFrom: 
            configMapKeyRef:
              name: APP-config-map
              key: dev_database_url
        - name: SECRET_KEY
          valueFrom: 
            configMapKeyRef:
              name: APP-config-map
              key: secret_key
        ports:
          - containerPort: 5000
            name: http
            protocol: TCP
        resources:
          requests:
            cpu: 400m
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: APP-service
  namespace: NAMESPACE
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "240"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  type: LoadBalancer
  selector:
    app: APP
  ports:
    - port: PORTNAME
      targetPort: 5000
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: APP-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: APP
    minReplicas: 2
    maxReplicas: 4
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60