apiVersion: batch/v1
kind: Job
metadata:
  name: "APP_NAME-migrate-job"
spec:
  backoffLimit: 2
  template:
    metadata:
      name: "migrate-job-APP_NAME"
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 240
      containers:
      - name: db-migrate
        image: ImageName
        command: 
        - /bin/bash
        - -c
        - sleep 30 &&
          echo "Begin Migration ..." &&
          python manage.py db migrate &&
          python manage.py db upgrade &&
          echo "Migration Completed" &&
          sleep 5    
        env:  
        - name: APP_SETTINGS
          valueFrom: 
            configMapKeyRef:
              name: APP_NAME-config-map
              key: app_settings
        - name: DEV_DATABASE_URL
          valueFrom: 
            configMapKeyRef:
              name: APP_NAME-config-map
              key: dev_database_url
        - name: SECRET_KEY
          valueFrom: 
            configMapKeyRef:
              name: APP_NAME-config-map
              key: secret_key